services:
  auth-service:
    build: .
    depends_on:
      - auth-db
    ports:
      - "${HOST_API_PORT}:8000"
    env_file:
      - .env
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${AUTH_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - auth-pgdata:/var/lib/postgresql/data

volumes:
  auth-pgdata:
